#!/usr/bin/env node
// Walks source/events/<folder> and generates assets/data/events.js — the
// single source of truth for events.html, event.html and the homepage's
// Recent Events strip. Run after tools/convert-images.mjs (it reads the
// already-converted files in assets/img/events/<slug>/ to build galleries).
//
// Events page has NO category grouping: each of the 14 folders is its own
// section. This script emits a flat EVENTS array sorted by date descending
// — that's the whole "grouping" there is.
//
// Run: node tools/scan-events.mjs

import { readdir, mkdir, writeFile, readFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseFolderName } from './lib/events-meta.mjs';
import { EVENT_COPY, DEFAULT_VENUE, COVER_OVERRIDES } from './lib/event-copy.mjs';

const ROOT = path.dirname(path.dirname(fileURLToPath(import.meta.url)));
const EVENTS_SRC = path.join(ROOT, 'source', 'events');
const EVENT_IMAGES_DIR = path.join(ROOT, 'assets', 'data', 'images', 'events');
const COVERS_JSON = path.join(ROOT, 'assets', 'data', 'images', 'event-covers.json');
const OUT_FILE = path.join(ROOT, 'assets', 'data', 'events.js');
const GALLERIES_DIR = path.join(ROOT, 'assets', 'data', 'galleries');

async function main() {
  let folders;
  try {
    folders = (await readdir(EVENTS_SRC, { withFileTypes: true })).filter(e => e.isDirectory()).map(e => e.name);
  } catch {
    throw new Error(`No source/events directory found at ${EVENTS_SRC}`);
  }

  const events = [];
  const reportRows = [];
  const covers = {};

  for (const folder of folders) {
    // Every failure below throws (not warns-and-continues) — a missing or
    // misparsed event must break the build loudly, never silently drop a
    // folder from the output.
    const meta = parseFolderName(folder); // throws with the folder name on any parse failure

    const copy = EVENT_COPY[meta.slug];
    if (!copy) {
      throw new Error(`No copy entry in tools/lib/event-copy.mjs for slug "${meta.slug}" (folder "${folder}")`);
    }

    let eventImages = {};
    try {
      eventImages = JSON.parse(await readFile(path.join(EVENT_IMAGES_DIR, `${meta.slug}.json`), 'utf8'));
    } catch {
      console.error(`WARNING: no image chunk for "${meta.slug}" — run tools/convert-images.mjs first. Continuing with an empty gallery.`);
    }
    const keys = Object.keys(eventImages).sort((a, b) => a.localeCompare(b, undefined, { numeric: true }));

    const gallery = keys.map(k => ({
      src: k, // canonical key into assets/data/images/events/<slug>.json — resolved via assets/js/img.js
      caption: '', // TODO: captions
      credit: ''
    }));

    const cover = COVER_OVERRIDES[meta.slug]
      ?? gallery.find(g => /cover|hero|main/i.test(g.src))?.src
      ?? gallery[0]?.src
      ?? '';
    if (cover && eventImages[cover]) covers[cover] = eventImages[cover];

    // The full gallery (one entry per photo — up to 170+ for some events)
    // lives in its own per-event file, fetched on demand rather than
    // inlined into events.js, so pages that only need titles/covers for
    // events they aren't currently showing full-size don't pull every
    // event's entire photo list.
    await mkdir(GALLERIES_DIR, { recursive: true });
    await writeFile(path.join(GALLERIES_DIR, `${meta.slug}.json`), JSON.stringify(gallery, null, 2));

    const event = {
      id: meta.slug,
      title: meta.title,
      date: meta.isoDate,
      venue: DEFAULT_VENUE,
      kicker: copy.kicker,
      excerpt: copy.excerpt,
      body: copy.body,
      cover,
      galleryCount: gallery.length,
      tags: copy.tags,
      ink: meta.ink
    };
    events.push(event);
    reportRows.push({ slug: meta.slug, iso: meta.isoDate, title: meta.title, images: gallery.length, sourceFolder: folder });
  }

  if (events.length !== folders.length) {
    throw new Error(`Parsed ${events.length} events but found ${folders.length} folders.`);
  }

  events.sort((a, b) => b.date.localeCompare(a.date));

  const missingImages = reportRows.filter(r => r.images === 0);

  const header = `// AUTO-GENERATED by tools/scan-events.mjs — do not hand-edit.
// Regenerate with: node tools/scan-events.mjs
// Shape mirrors a REST response: GET /api/events (sorted by date, descending)
// Each event's full photo gallery lives separately at
// assets/data/galleries/<slug>.json (GET /api/events/{slug}/gallery),
// fetched on demand — see assets/js/pages/event.js and events.js.
`;
  const body = `export const EVENTS = ${JSON.stringify(events, null, 2)};\n`;

  await mkdir(path.dirname(OUT_FILE), { recursive: true });
  await writeFile(OUT_FILE, header + body);
  await writeFile(COVERS_JSON, JSON.stringify(covers, null, 2));

  console.log('\n=== Event scan report ===');
  console.log(`Folders found: ${folders.length}`);
  console.log(`Events parsed: ${events.length}\n`);
  console.log('slug'.padEnd(46) + 'date'.padEnd(12) + 'images'.padEnd(8) + 'title');
  for (const r of events) {
    console.log(r.id.padEnd(46) + r.date.padEnd(12) + String(r.galleryCount).padEnd(8) + r.title);
  }
  if (missingImages.length) {
    console.log(`\nWARNING: ${missingImages.length} event(s) have zero images — run tools/convert-images.mjs first if this is unexpected:`);
    for (const r of missingImages) console.log(`  - ${r.slug} (${r.sourceFolder})`);
  }
  console.log(`\nAll ${events.length}/${folders.length} folders parsed successfully.`);
  console.log(`Written to ${path.relative(ROOT, OUT_FILE)}`);
  console.log(`Cover image metadata (${Object.keys(covers).length} entries) written to ${path.relative(ROOT, COVERS_JSON)}`);
  console.log(`Per-event galleries written to ${path.relative(ROOT, GALLERIES_DIR)}`);
}

main().catch(err => { console.error(`FATAL: ${err.message}`); process.exit(1); });
